# Generated by Django 5.1.7 on 2025-04-23 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_notificationlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
