# Generated by Django 5.1.7 on 2025-04-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cabinet',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shelf',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
