# Generated by Django 5.1.7 on 2025-04-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_product_cabinet_product_shelf'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('devices', models.CharField(help_text='Bu ürünün kullanıldığı cihazlar (virgülle ayrılmış).', max_length=500)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
