# Generated by Django 5.1.7 on 2025-04-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
