# Generated by Django 5.1.7 on 2025-04-26 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_devicecomponent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('acil', 'Acil'), ('rutin', 'Rutin')], max_length=10)),
                ('installed_at', models.DateTimeField()),
                ('removed_at', models.DateTimeField(blank=True, help_text='Bu cihaz bloğu söküldüyse tarih', null=True)),
                ('components', models.ManyToManyField(related_name='installations', to='inventory.devicecomponent')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='inventory.institution')),
            ],
        ),
    ]
