# Generated by Django 5.1.7 on 2025-04-26 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_installation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(help_text='Notu düşen kişinin adı', max_length=200)),
                ('content', models.TextField(help_text='Cihaz parçası için not')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Notun oluşturulma zamanı')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='inventory.devicecomponent')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(help_text='Notu düşen kişinin adı', max_length=200)),
                ('content', models.TextField(help_text='Kurum için not')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Notun oluşturulma zamanı')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='inventory.institution')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_by', models.CharField(help_text='Bakımı yapan kişinin adı', max_length=200)),
                ('performed_at', models.DateTimeField(help_text='Bakım tarihi ve saati')),
                ('notes', models.TextField(blank=True, help_text='Bakım sırasında not düştüyse buraya')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='inventory.devicecomponent')),
            ],
        ),
    ]
