# Generated by Django 5.1.7 on 2025-04-26 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_componentnote_institutionnote_maintenancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('requires_core', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='devicecomponent',
            name='current_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='inventory.institution'),
        ),
        migrations.AlterField(
            model_name='componentnote',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='componentnote',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='componentnote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institutionnote',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='institutionnote',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='institutionnote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='performed_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='performed_by',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='devicecomponent',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='components', to='inventory.devicetype'),
        ),
    ]
