# Generated by Django 5.1.7 on 2025-04-26 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_devicetype_devicecomponent_current_institution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicecomponent',
            name='current_institution',
        ),
        migrations.RemoveField(
            model_name='devicecomponent',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='component',
        ),
        migrations.RemoveField(
            model_name='installation',
            name='components',
        ),
        migrations.RemoveField(
            model_name='installation',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='institutionnote',
            name='institution',
        ),
        migrations.DeleteModel(
            name='ComponentNote',
        ),
        migrations.DeleteModel(
            name='DeviceType',
        ),
        migrations.DeleteModel(
            name='MaintenanceRecord',
        ),
        migrations.DeleteModel(
            name='DeviceComponent',
        ),
        migrations.DeleteModel(
            name='Installation',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
        migrations.DeleteModel(
            name='InstitutionNote',
        ),
    ]
