# Generated by Django 5.1.7 on 2025-04-26 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_devicecomponent_devicetype_institution_componentnote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(help_text='Notu giren kişi', max_length=200)),
                ('content', models.TextField(help_text='Kurulum sırasında alınan not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='inventory.installation')),
            ],
        ),
        migrations.DeleteModel(
            name='InstitutionNote',
        ),
    ]
