# Generated by Django 5.1.7 on 2025-04-26 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_installationnote_delete_institutionnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceFault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_at', models.DateTimeField()),
                ('reported_by', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Arıza sebebi / notu')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, help_text='Çözüm notu')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faults', to='inventory.devicecomponent')),
            ],
        ),
    ]
