# Generated by Django 5.1.7 on 2025-04-29 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_remove_devicecomponent_current_institution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Cihaz Adı')),
                ('category', models.CharField(max_length=100, verbose_name='Tip')),
                ('core_required', models.BooleanField(default=False, verbose_name='Core Bağımlılığı')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kurum Adı')),
                ('city', models.CharField(max_length=100, verbose_name='Şehir')),
                ('contact_name', models.CharField(max_length=200, verbose_name='İrtibat Kişisi')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Telefon')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Seri No')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='inventory.devicetype')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='inventory.institution')),
            ],
        ),
    ]
