# Generated by Django 5.1.7 on 2025-04-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_devicetype_institution_devicerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='is_core',
            field=models.BooleanField(default=False, verbose_name='CORE'),
        ),
    ]
