# Generated by Django 5.1.7 on 2025-04-29 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_devicetype_is_core'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('install_date', models.DateField(verbose_name='Kurulum Tarihi')),
                ('uninstall_date', models.DateField(blank=True, help_text='Boşsa hâlen kurulu', null=True, verbose_name='Söküm Tarihi')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='inventory.devicerecord', verbose_name='Cihaz')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='inventory.institution', verbose_name='Kurum')),
            ],
        ),
    ]
