# Generated by Django 5.1.7 on 2025-05-01 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_installation'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='connected_core',
            field=models.ForeignKey(blank=True, limit_choices_to={'device_type__is_core': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_installations', to='inventory.devicerecord', verbose_name='Bağlı Core'),
        ),
    ]
