# Generated by Django 5.1.7 on 2025-05-01 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_installation_connected_core'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Bakım Tarihi')),
                ('personnel', models.CharField(help_text='İsimleri virgülle ayırarak girin', max_length=255, verbose_name='Bakımı Yapanlar')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='inventory.devicerecord', verbose_name='Cihaz')),
            ],
        ),
    ]
