# Generated by Django 5.1.7 on 2025-05-01 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_maintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_date', models.DateField(verbose_name='Müdahale Tarihi')),
                ('technician', models.CharField(help_text='İsimleri virgülle ayırarak girin', max_length=255, verbose_name='Müdahale Eden')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('closed_date', models.DateField(blank=True, help_text='Boşsa açık (open), doluysa kapalı (closed)', null=True, verbose_name='Kapatılma Tarihi')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faults', to='inventory.devicerecord', verbose_name='Cihaz')),
            ],
        ),
    ]
