# Generated by Django 5.1.7 on 2025-05-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_fault'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fault',
            name='notes',
        ),
        migrations.AddField(
            model_name='fault',
            name='closing_notes',
            field=models.TextField(blank=True, help_text='Arıza kapatılırken eklenen notlar', verbose_name='Kapanış Notları'),
        ),
        migrations.AddField(
            model_name='fault',
            name='initial_notes',
            field=models.TextField(blank=True, help_text='İlk müdahalede alınan notlar', verbose_name='Müdahale Notları'),
        ),
    ]
