# Generated by Django 5.1.7 on 2025-05-01 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_remove_fault_notes_fault_closing_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_date', models.DateField(help_text='Notun alındığı tarih', verbose_name='Not Tarihi')),
                ('text', models.TextField(help_text='Kurumla ilgili serbest metin', verbose_name='Not Metni')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='inventory.institution', verbose_name='Kurum')),
            ],
        ),
    ]
