# Generated by Django 5.1.7 on 2025-05-01 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_institutionnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionnote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institution_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='institutionnote',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='inventory.institution'),
        ),
        migrations.AlterField(
            model_name='institutionnote',
            name='note_date',
            field=models.DateField(auto_now_add=True, help_text='Notun alındığı tarih', verbose_name='Not Tarihi'),
        ),
    ]
