# Generated by Django 5.1.7 on 2025-05-03 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_institutionnote_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicerecord',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.devicetype'),
        ),
        migrations.AlterField(
            model_name='devicerecord',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_records', to='inventory.institution'),
        ),
        migrations.AlterField(
            model_name='devicerecord',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
