# Generated by Django 5.1.7 on 2025-05-27 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_usedpart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsedPart',
        ),
    ]
